### ISSUE TITLE
enhancement o have a verbose headless

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.clients#5]
bash gama-headless.sh -socket 6868 -v doesn't work so far.

When run in verbose the client doesn't run

**Comment by AlexisDrogoul** [comment]
Probably not the good error message !

**Comment by hqnghi88** [comment]
@[agrignard](https://github.com/agrignard) agrignard deleted a comment from [AlexisDrogoul](https://github.com/AlexisDrogoul) [19 hours ago](https://github.com/gama-platform/gama.client/issues/5#event-9015938844) what did you commented @AlexisDrogoul ?

**Comment by AlexisDrogoul** [comment]
😉 I was saying that the error displayed by @agrignard was not relevant to the issue.

**Comment by agrignard** [comment]
I pasted the wrong error message so I udpated my initial issue and deleted Alexis comment. Actually i cannot paste any message error as the verbose mode doesn't not work ;)

I'll dig it a bit more this issue and commit the corresponding gama model to facilitate the reproduction of this issue

**Comment by hqnghi88** [comment]
It is only mac (both intel and m1) and terminal type. I used to develop reactjs and server -v on my m1 but it works well

**Comment by hqnghi88** [comment]
https://github.com/gama-platform/gama/issues/3766 relating with the launching script. Please wait to test when the origine issue will be fixed

**Comment by lesquoyb** [comment]
should be fixed by [https://github.com/gama-platform/gama/commit/a004b640e6f27669f2b889290682d8e65faea9eb](https://github.com/gama-platform/gama/commit/a004b640e6f27669f2b889290682d8e65faea9eb)
Please reopen if it's still happening
